const INITIAL_USERS = [
  { id: 1, username: "admin", fullName: "Bhanu Prasad (Admin)", role: "Admin" },
  { id: 2, username: "kiran", fullName: "Kiran Kumar", role: "Distributor" },
  { id: 3, username: "srinivas", fullName: "Srinivas Rao", role: "Distributor" },
  { id: 4, username: "anjali", fullName: "Anjali Devi", role: "Distributor" }
];

const INITIAL_GUESTS = [
  // --- HYDERABAD CLUSTER ---
  {
    id: 101,
    name: "Kondapalli Venkata Ramana",
    mobile: "9848022338",
    familyMembers: 4,
    village: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Flat 402, Royal Palms Residency, Road No. 36, Jubilee Hills, Hyderabad",
    latitude: 17.4325,
    longitude: 78.4074,
    notes: "Close friend of bride's father. Hand-deliver only.",
    status: "Distributed",
    assignedTo: "Kiran Kumar",
    distributedDate: "2026-05-28",
    distributedTime: "11:30",
    remarks: "Delivered personally to Ramana Garu. He was very happy."
  },
  {
    id: 102,
    name: "Yerra Satyanarayana Chowdary",
    mobile: "9440123456",
    familyMembers: 5,
    village: "Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Plot No. 89, Kavuri Hills Phase 2, Madhapur, Hyderabad",
    latitude: 17.4432,
    longitude: 78.3888,
    notes: "Requires VIP card (Velvet Box edition).",
    status: "Assigned",
    assignedTo: "Kiran Kumar",
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 103,
    name: "Meka Srinivasa Rao",
    mobile: "9989012345",
    familyMembers: 3,
    village: "Gachibowli",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Villa 12, Rainbow Vistas, Financial District, Gachibowli, Hyderabad",
    latitude: 17.4401,
    longitude: 78.3489,
    notes: "Confirm arrival date for travel arrangements.",
    status: "Pending",
    assignedTo: null,
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 104,
    name: "Gundavarapu Lakshmi Kumari",
    mobile: "9177098765",
    familyMembers: 2,
    village: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Door No. 8-2-120/A, Road No. 10, Jubilee Hills, Hyderabad",
    latitude: 17.4288,
    longitude: 78.4121,
    notes: "Aunt of the groom.",
    status: "Distributed",
    assignedTo: "Anjali Devi",
    distributedDate: "2026-05-29",
    distributedTime: "16:45",
    remarks: "Delivered to her daughter as she was at the temple."
  },
  {
    id: 105,
    name: "Pendurthi Subba Rao",
    mobile: "9866045312",
    familyMembers: 6,
    village: "Kukatpally",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Fl-103, Balaji Towers, KPHB Colony 3rd Phase, Kukatpally, Hyderabad",
    latitude: 17.4842,
    longitude: 78.3976,
    notes: "Big family, send standard family invitation.",
    status: "Assigned",
    assignedTo: "Srinivas Rao",
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 106,
    name: "Vangaveeti Mohana Krishna",
    mobile: "9959065432",
    familyMembers: 4,
    village: "Madhapur",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Flat 5A, Cyber Heights, Image Gardens Road, Madhapur, Hyderabad",
    latitude: 17.4475,
    longitude: 78.3842,
    notes: "Call before visiting, works at an IT firm.",
    status: "Assigned",
    assignedTo: "Kiran Kumar",
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 107,
    name: "Adusumilli Rajendra Prasad",
    mobile: "9848555666",
    familyMembers: 5,
    village: "Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "House 45, Near Apollo Hospital, Film Nagar, Jubilee Hills, Hyderabad",
    latitude: 17.4215,
    longitude: 78.4095,
    notes: "VIP Guest.",
    status: "Pending",
    assignedTo: null,
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 108,
    name: "Parvathaneni Rama Chandra Rao",
    mobile: "9490112233",
    familyMembers: 3,
    village: "Secunderabad",
    city: "Hyderabad",
    state: "Telangana",
    fullAddress: "Q.No. 12-10-56/1, West Marredpally, Secunderabad",
    latitude: 17.4492,
    longitude: 78.4988,
    notes: "Paternal uncle.",
    status: "Distributed",
    assignedTo: "Srinivas Rao",
    distributedDate: "2026-05-30",
    distributedTime: "10:15",
    remarks: "Delivered. Had traditional filter coffee with him."
  },

  // --- VIJAYAWADA CLUSTER ---
  {
    id: 201,
    name: "Gogineni Venkateswara Rao",
    mobile: "9848123123",
    familyMembers: 5,
    village: "Benz Circle",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    fullAddress: "Flat 202, Siddhartha Enclave, Near Benz Circle, Vijayawada",
    latitude: 16.5022,
    longitude: 80.6432,
    notes: "Business associate. Hand-deliver.",
    status: "Distributed",
    assignedTo: "Srinivas Rao",
    distributedDate: "2026-05-25",
    distributedTime: "18:00",
    remarks: "Handed over at his office. Very warm reception."
  },
  {
    id: 202,
    name: "Vuyyuru Satish Babu",
    mobile: "9885112233",
    familyMembers: 4,
    village: "Patamata",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    fullAddress: "House No. 40-5-18, Tikkle Road, Patamata, Vijayawada",
    latitude: 16.5015,
    longitude: 80.6558,
    notes: "Maternal uncle.",
    status: "Pending",
    assignedTo: null,
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 203,
    name: "Nimmagadda Rajesh",
    mobile: "9912345678",
    familyMembers: 3,
    village: "One Town",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    fullAddress: "Door No. 11-23-45, Canal Road, One Town, Vijayawada",
    latitude: 16.5182,
    longitude: 80.6122,
    notes: "Old family friend.",
    status: "Assigned",
    assignedTo: "Srinivas Rao",
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 204,
    name: "Vallabhaneni Hima Bindu",
    mobile: "8886677889",
    familyMembers: 2,
    village: "Governorpet",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    fullAddress: "Flat 101, Srinivasa Residency, Eluru Road, Governorpet, Vijayawada",
    latitude: 16.5121,
    longitude: 80.6289,
    notes: "Bride's college roommate.",
    status: "Pending",
    assignedTo: null,
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 205,
    name: "Kanneganti Samba Siva Rao",
    mobile: "9440654321",
    familyMembers: 5,
    village: "Patamata",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    fullAddress: "Plot 34, Teacher's Colony, Near NTR Circle, Patamata, Vijayawada",
    latitude: 16.4952,
    longitude: 80.6621,
    notes: "Senior family elder.",
    status: "Distributed",
    assignedTo: "Srinivas Rao",
    distributedDate: "2026-05-26",
    distributedTime: "12:30",
    remarks: "Delivered. Took blessings."
  },
  {
    id: 206,
    name: "Katragadda Anila",
    mobile: "9123450987",
    familyMembers: 3,
    village: "Benz Circle",
    city: "Vijayawada",
    state: "Andhra Pradesh",
    fullAddress: "Flat 503, Legend Heights, Near Jyothi Mahal, Vijayawada",
    latitude: 16.5055,
    longitude: 80.6401,
    notes: "Will visit on weekend.",
    status: "Assigned",
    assignedTo: "Anjali Devi",
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },

  // --- VISAKHAPATNAM CLUSTER ---
  {
    id: 301,
    name: "Palla Appala Naidu",
    mobile: "9866112233",
    familyMembers: 6,
    village: "Gajuwaka",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    fullAddress: "House No. 26-12-89, Chinagantyada, Gajuwaka, Visakhapatnam",
    latitude: 17.6912,
    longitude: 83.2105,
    notes: "Groom's cousin. Hand-deliver card and sweet box.",
    status: "Distributed",
    assignedTo: "Anjali Devi",
    distributedDate: "2026-05-24",
    distributedTime: "15:00",
    remarks: "Delivered both card and sweet box. Confirmed they are coming."
  },
  {
    id: 302,
    name: "Biddika Satyam",
    mobile: "9491123450",
    familyMembers: 4,
    village: "MVP Colony",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    fullAddress: "Sector 3, Plot 142, MVP Colony, Visakhapatnam",
    latitude: 17.7422,
    longitude: 83.3325,
    notes: "Groom's high school teacher.",
    status: "Pending",
    assignedTo: null,
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 303,
    name: "Gedela Vasudeva Rao",
    mobile: "9908011223",
    familyMembers: 3,
    village: "Dwaraka Nagar",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    fullAddress: "D.No. 47-10-15, 3rd Lane, Dwaraka Nagar, Visakhapatnam",
    latitude: 17.7214,
    longitude: 83.3055,
    notes: "Close family friend.",
    status: "Assigned",
    assignedTo: "Anjali Devi",
    distributedDate: null,
    distributedTime: null,
    remarks: ""
  },
  {
    id: 304,
    name: "Sankuratri Sarada",
    mobile: "8008123456",
    familyMembers: 2,
    village: "MVP Colony",
    city: "Visakhapatnam",
    state: "Andhra Pradesh",
    fullAddress: "Flat B4, Sea Sands Apartments, Sector 1, MVP Colony, Visakhapatnam",
    latitude: 17.7465,
    longitude: 83.3392,
    notes: "Bride's aunt. Requires direct drop.",
    status: "Distributed",
    assignedTo: "Anjali Devi",
    distributedDate: "2026-05-24",
    distributedTime: "17:30",
    remarks: "Delivered. Handed over invitation."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { INITIAL_USERS, INITIAL_GUESTS };
}
